#' AusTraits Data Portal Server Logic
#'
#' @param input Input list generated by Shiny
#' @param output Output list generated by Shiny
#' @param session Session id for Shiny interaction

app_server <- function(input, output, session) {
  # Reactive value to store the filtered data later
  filtered_database <- reactiveVal(NULL)
  filtered_query_cache <- reactiveVal(NULL)
  full_filtered_cache <- reactiveVal(NULL)

  # Reactive datasets that switch based on user selection
  current_austraits <- reactive({
    if (filters()$dataset_type == "species") {
      austraits_species_duckdb
    } else {
      austraits_duckdb
    }
  })

  current_austraits_display <- reactive({
    if (filters()$dataset_type == "species") {
      austraits_species_display_duckdb
    } else {
      austraits_display_duckdb
    }
  })

  current_columns_display <- reactive({
    if (filters()$dataset_type == "species") {
      columns_display_species
    } else {
      columns_display
    }
  })
  
  # Initialize dropdown choices
  taxon_name_choices <- reactive({
    dropdowns$all_taxon_names
  })
  genus_choices <- reactive({
    dropdowns$all_genus
  })
  family_choices <- reactive({
    dropdowns$all_family
  })

  # Start telemetry session
  start_telemetry_session()

# Update the appropriate selectizeInput when radio button changes
filters <- mod_filters_server(
  "filters",
  filtered_database,
  family_choices = family_choices,
  genus_choices = genus_choices,
  taxon_name_choices = taxon_name_choices
)
observeEvent(input[["filters-clear_filters"]], {
  updateSelectizeInput(session, "filters-trait_name", selected = character(0))
  updateSelectizeInput(session, "filters-basis_of_record", selected = character(0))
  updateSelectizeInput(session, "filters-life_stage", selected = character(0))
  updateSelectizeInput(session, "filters-apc_taxon_distribution", selected = character(0))
  
  # Force reload of all data after clearing
  Sys.sleep(0.1)  # Small delay to let inputs clear
  filtered_database(NULL)
})
  
  # Server-side selectizeInput update for other options that are not conditional
  updateSelectizeInput(session, "filters-trait_name", choices = dropdowns$all_traits, server = TRUE)
  updateSelectizeInput(session, "filters-trait_grouping", choices = dropdowns$all_trait_groupings, server = TRUE)
  updateSelectizeInput(session, "filters-structure_measured", choices = dropdowns$all_structure_measured, server = TRUE)
  updateSelectizeInput(session, "filters-keywords", choices = dropdowns$all_keywords, server = TRUE)
  updateSelectizeInput(session, "filters-basis_of_record", choices = dropdowns$all_bor, server = TRUE)
  updateSelectizeInput(session, "filters-life_stage", choices = dropdowns$all_age, server = TRUE)

  # Update trait names when trait features are selected
  observeEvent(
    list(
      input[["filters-trait_grouping"]],
      input[["filters-structure_measured"]],
      input[["filters-keywords"]]
    ),
    {
      # Get current selections
      selected_grouping <- input[["filters-trait_grouping"]]
      selected_structure <- input[["filters-structure_measured"]]
      selected_keywords <- input[["filters-keywords"]]
      
      # If any trait feature is selected, filter traits
      if (!is.null(selected_grouping) && length(selected_grouping) > 0 ||
          !is.null(selected_structure) && length(selected_structure) > 0 ||
          !is.null(selected_keywords) && length(selected_keywords) > 0) {
        
        # Use cached helper function
        matching_traits <- get_matching_traits_cached(
          trait_groups,
          selected_grouping,
          selected_structure,
          selected_keywords
        )
        
        # Update trait_name dropdown
        current_trait_selection <- input[["filters-trait_name"]]
        updateSelectizeInput(session, "filters-trait_name",
                            choices = matching_traits,
                            selected = current_trait_selection,
                            server = TRUE)
      } else {
        # No trait features selected - show all traits
        current_trait_selection <- input[["filters-trait_name"]]
        updateSelectizeInput(session, "filters-trait_name",
                            choices = dropdowns$all_traits,
                            selected = current_trait_selection,
                            server = TRUE)
      }
    },
    ignoreInit = TRUE
  )

  # Populate custom column filters (using predefined list from global.R)
  updateSelectizeInput(session, "filters-custom_col_1", 
                      choices = custom_filter_columns, 
                      selected = character(0),
                      server = TRUE)
  updateSelectizeInput(session, "filters-custom_col_2", 
                      choices = custom_filter_columns,
                      selected = character(0),
                      server = TRUE)
  updateSelectizeInput(session, "filters-custom_col_3", 
                      choices = custom_filter_columns,
                      selected = character(0),
                      server = TRUE)

  # Update custom filter columns based on dataset type
  observeEvent(input[["filters-dataset_type"]], {
    cols <- if (input[["filters-dataset_type"]] == "species") {
      custom_filter_columns_species
    } else {
      custom_filter_columns
    }
    
    updateSelectizeInput(session, "filters-custom_col_1", 
                        choices = cols, 
                        selected = character(0), 
                        server = TRUE)
    updateSelectizeInput(session, "filters-custom_col_2", 
                        choices = cols, 
                        selected = character(0), 
                        server = TRUE)
    updateSelectizeInput(session, "filters-custom_col_3", 
                        choices = cols, 
                        selected = character(0), 
                        server = TRUE)
  })


  # When column selected, populate values (only for controlled vocab)
  for (i in 1:3) {
    local({
      num <- i
      observeEvent(input[[paste0("filters-custom_col_", num)]], {
        req(input[[paste0("filters-custom_col_", num)]])
        
        column_name <- input[[paste0("filters-custom_col_", num)]]
        
        # Only populate dropdown for controlled vocabulary columns
        if (column_name %in% controlled_vocab_columns) {
          # ALWAYS use full dataset query, not just loaded 100 rows
          query <- filtered_query_cache()

          if (!is.null(query) && column_name %in% names(query)) {
            # Special handling for dataset_id in species averages
            if (column_name == "dataset_id" && filters()$dataset_type == "species") {
              unique_values <- dropdowns$all_dataset_ids_species
            } else {
              # Use cached helper with limit to avoid large collect operations
              unique_values <- get_distinct_values_cached(query, column_name, limit = 1000)
            }
          } else {
            # Special handling for dataset_id in species averages
            if (column_name == "dataset_id" && filters()$dataset_type == "species") {
              unique_values <- dropdowns$all_dataset_ids_species
            } else {
              # Use cached helper with limit
              unique_values <- get_distinct_values_cached(current_austraits_display(), column_name, limit = 1000)
            }
          }
          
          updateSelectizeInput(session, paste0("filters-custom_val_", num), 
                              choices = unique_values, 
                              server = TRUE,
                              selected = NULL)
        }
        # For free text columns, no need to populate (user types freely)
      })
    })
  }
  
  # Apply Filter
  observeEvent(filters(), {
    
    # SAFETY CHECK: Wait for data to be loaded
    req(exists("austraits_display") || exists("austraits_species_display"))
    if (!exists("austraits_display") && !exists("austraits_species_display")) return()

    # Extract filters once
    filter_vals <- filters()

    # Check which filters are valid
    valid_filter_names <- valid_filters(filter_vals)

    has_filters <- any(
      sapply(valid_filter_names, function(name) {
        has_input_value(filter_vals, name)
      })
    )

    if (has_filters) {

      print("filtering")
      
      tryCatch({
        # Apply filters but don't collect yet
        filtered_query <- current_austraits_display() |>
          apply_filters_categorical(filter_vals) |>
          apply_filters_location(filter_vals)
        
        # Get total count (fast - just counts, doesn't load data)
        total_rows <- filtered_query |> 
          dplyr::count() |> 
          dplyr::collect() |> 
          dplyr::pull(n)
        
        # Only use lazy loading for large datasets (> 10,000 rows)
        if (total_rows > 10000) {
          # Load first 100 rows only (use head() for DuckDB)
          filtered_data <- filtered_query |> 
            head(100) |> 
            dplyr::collect()
          
          print(paste("done - showing 100 of", total_rows, "rows"))
        } else {
          # Load all data for small datasets
          filtered_data <- filtered_query |> 
            dplyr::collect()
          
          print(paste("done - showing all", total_rows, "rows"))
        }
        
        # Add total_rows as attribute
        attr(filtered_data, "total_rows") <- total_rows
        # Query for loading more rows later
        filtered_query_cache(filtered_query)

        # Clear the full cache when filters change
        full_filtered_cache(NULL)

        # Store filtered data
        filtered_database(filtered_data)
        
      }, error = function(e) {
        cat("\n!!! FILTERING ERROR !!!\n")
        cat("Error:", e$message, "\n")
        cat("Available columns:", paste(names(austraits_display), collapse=", "), "\n")
        filtered_database(NULL)
      })

    } else {

      if (filter_vals$taxon_rank != "all") {
        filtered_database(NULL)
      }
    }
  })
    
  # Display all data when all taxa are selected
  observeEvent(filters()$taxon_rank, {

    if (filters()$taxon_rank == "all" || filters()$taxon_rank == "") {
      
      # Get current filter values
      filter_vals <- filters()
      
      # Check if there are other filters applied (trait, location, etc.)
      has_other_filters <- any(
        !is.null(filter_vals$trait_name) && length(filter_vals$trait_name) > 0,
        !is.null(filter_vals$trait_grouping) && length(filter_vals$trait_grouping) > 0,  # ADD
        !is.null(filter_vals$structure_measured) && length(filter_vals$structure_measured) > 0,  # ADD
        !is.null(filter_vals$keywords) && length(filter_vals$keywords) > 0,  # ADD
        !is.null(filter_vals$basis_of_record) && length(filter_vals$basis_of_record) > 0,
        !is.null(filter_vals$life_stage) && length(filter_vals$life_stage) > 0,
        !is.null(filter_vals$location) && length(filter_vals$location) > 0 && filter_vals$location != "",
        !is.null(filter_vals$apc_taxon_distribution) && length(filter_vals$apc_taxon_distribution) > 0,
        (!is.null(filter_vals$min_latitude) && !is.na(as.numeric(filter_vals$min_latitude))) ||
        (!is.null(filter_vals$max_latitude) && !is.na(as.numeric(filter_vals$max_latitude))) ||
        (!is.null(filter_vals$min_longitude) && !is.na(as.numeric(filter_vals$min_longitude))) ||
        (!is.null(filter_vals$max_longitude) && !is.na(as.numeric(filter_vals$max_longitude))),
        !is.null(filter_vals$custom_col_1) && !is.null(filter_vals$custom_val_1) &&
        !is.null(filter_vals$custom_col_1) && !is.null(filter_vals$custom_val_1) && 
          (length(filter_vals$custom_val_1) > 0) && (nchar(paste(filter_vals$custom_val_1, collapse="")) > 0),
        !is.null(filter_vals$custom_col_2) && !is.null(filter_vals$custom_val_2) && 
          (length(filter_vals$custom_val_2) > 0) && (nchar(paste(filter_vals$custom_val_2, collapse="")) > 0),
        !is.null(filter_vals$custom_col_3) && !is.null(filter_vals$custom_val_3) && 
          (length(filter_vals$custom_val_3) > 0) && (nchar(paste(filter_vals$custom_val_3, collapse="")) > 0)
      )
      
      if (has_other_filters) {
        filtered_query <- current_austraits_display() |>
          apply_filters_categorical(filter_vals) |>
          apply_filters_location(filter_vals)
        
        # Get total count
        total_rows <- filtered_query |> 
          dplyr::count() |> 
          dplyr::collect() |> 
          dplyr::pull(n)
        
        # Only use lazy loading for large datasets
        if (total_rows > 10000) {
          filtered_data <- filtered_query |> 
            head(100) |> 
            dplyr::collect()
        } else {
          filtered_data <- filtered_query |> 
            dplyr::collect()
        }
        
        attr(filtered_data, "total_rows") <- total_rows
        filtered_query_cache(filtered_query)
        full_filtered_cache(NULL)
        
        filtered_database(filtered_data)
      } else {
        # Show full database
        all_data_query <- current_austraits_display()
        
        # Get total count
        total_rows <- all_data_query |> 
          dplyr::count() |> 
          dplyr::collect() |> 
          dplyr::pull(n)
        
        # Only use lazy loading for large datasets
        if (total_rows > 10000) {
          full_display_database <- all_data_query |> 
            head(100) |> 
            dplyr::collect()
        } else {
          full_display_database <- all_data_query |> 
            dplyr::collect()
        }
        
        attr(full_display_database, "total_rows") <- total_rows
        filtered_query_cache(all_data_query)
        full_filtered_cache(NULL)
        
        filtered_database(full_display_database)
      }

    } else {
      if (is.null(filtered_database())) {
        return()
      }
    }
  })
    
  # Set up download data as reactive expression
  download_data_table <- reactive({
    # Use the query cache to get ALL filtered data, not just displayed 100 rows
    query <- filtered_query_cache()
    
    if (is.null(query)) {
      return(NULL)
    }
    
    # If user applied DataTable column filters, respect those
    if (!is.null(data_table_outputs$visible_rows())) {
      visible_rows <- data_table_outputs$visible_rows()
      display_db <- filtered_database()
      
      if (!is.null(display_db) && length(visible_rows) > 0 && length(visible_rows) < nrow(display_db)) {
        # User filtered within the DataTable - only download those rows
        display_db_filtered <- display_db[visible_rows, , drop = FALSE]
        return(current_austraits() |> dplyr::semi_join(display_db_filtered, by = "row_id"))
      }
    }
    
    # Default: Return ALL filtered data from the query (not just 100 displayed)
    # Collect ALL row_ids from the filtered query, then join with full dataset
    filtered_row_ids <- query |> 
      dplyr::select(row_id) |> 
      dplyr::collect()
    
    # Join full dataset with ALL filtered row_ids
    current_austraits() |> dplyr::semi_join(filtered_row_ids, by = "row_id")
  })
  
  # Data table module
  data_table_outputs <- mod_data_table_server("data_table", filtered_database, filtered_query_cache, current_columns_display)

# Reset pagination whenever filtered data changes (e.g. new filter)
  observeEvent(filtered_database(), {
    req(filtered_database())
    data_table_outputs$set_start(0)

    # Log search event
    log_telemetry_event("search", details = list(
    dataset_type = filters()$dataset_type,
    trait = filters()$trait_name
  ))
  }, ignoreInit = TRUE)

  # Handle loading more data - with throttle to prevent rapid firing
  last_load_time <- reactiveVal(Sys.time())

  observeEvent(data_table_outputs$load_more_click(), {
    req(filtered_query_cache())
    
    current_data <- filtered_database()
    if (is.null(current_data)) return()
    
    total_loaded <- nrow(current_data)
    total_rows <- attr(current_data, "total_rows")
    
    if (is.null(total_rows) || total_loaded >= total_rows) return()
    
    cat("Loading next 100 rows... Currently have", total_loaded, "of", total_rows, "\n")
    
    # Check if we have full data cached
    cached_data <- full_filtered_cache()
    
    if (is.null(cached_data)) {
      cat("Caching full filtered dataset (this may take a moment)...\n")
      query <- filtered_query_cache()
      cached_data <- query |> dplyr::collect()
      full_filtered_cache(cached_data)
      cat("Cached", nrow(cached_data), "total rows\n")
    }
    
    # Get next 100 rows from cache
    end_row <- min(total_loaded + 100, nrow(cached_data))
    next_batch <- cached_data[(total_loaded + 1):end_row, ]
    
    cat("Loaded", nrow(next_batch), "new rows from cache\n")
    
    if (nrow(next_batch) > 0) {
      new_data <- dplyr::bind_rows(current_data, next_batch)
      attr(new_data, "total_rows") <- total_rows
      
      # Tell DT where to start (row index)
      data_table_outputs$set_start(total_loaded)

      # Re-render with more rows
      filtered_database(new_data)
      
      cat("Total rows now:", nrow(new_data), "\n")
    }
  }, ignoreInit = TRUE)

  # Citations module
  usage_text_reactive <- mod_citations_server("citations", filtered_query_cache)

  # App info module
  mod_app_info_server("app_info")

  # Taxon view module
  mod_taxon_view_server("taxon_view", filters, filtered_database, reactive(input$main_tabs))

  # Trait view module
  mod_trait_view_server("trait_view", filtered_query_cache, filters)

  # URL Query Parameter Handler - Load filters from URL on app startup
  url_processed <- reactiveVal(FALSE)

  observe({
    # Only run once
    if (url_processed()) return()
    
    query <- parseQueryString(session$clientData$url_search)
    
    # Only process if query parameters exist
    if (length(query) > 0) {
      
      # Handle taxon rank first
      if (!is.null(query$taxon_rank) && query$taxon_rank %in% c("all", "family", "genus", "taxon_name")) {
        updateRadioButtons(session, "filters-taxon_rank", selected = query$taxon_rank)
      }
      
      # Handle taxon selections WITH CHOICES
      if (!is.null(query$family)) {
        updateSelectizeInput(session, "filters-family", 
                            choices = family_choices(), 
                            selected = query$family, 
                            server = TRUE)
      }
      
      if (!is.null(query$genus)) {
        updateSelectizeInput(session, "filters-genus", 
                            choices = genus_choices(), 
                            selected = query$genus, 
                            server = TRUE)
      }
      
      if (!is.null(query$taxon_name)) {
        updateSelectizeInput(session, "filters-taxon_name", 
                            choices = taxon_name_choices(), 
                            selected = query$taxon_name, 
                            server = TRUE)
      }
      
      # Handle trait name WITH CHOICES
      if (!is.null(query$trait_name)) {
        updateSelectizeInput(session, "filters-trait_name", 
                            choices = dropdowns$all_traits, 
                            selected = query$trait_name, 
                            server = TRUE)
      }
      
      # Handle location filters
      if (!is.null(query$location) && query$location %in% c("georeferenced", "apc")) {
        updateRadioButtons(session, "filters-location", selected = query$location)
      }
      
      if (!is.null(query$apc_taxon_distribution)) {
        states <- strsplit(query$apc_taxon_distribution, ",")[[1]]
        updateSelectizeInput(session, "filters-apc_taxon_distribution", 
                            choices = dropdowns$all_states_territories, 
                            selected = states, 
                            server = TRUE)
      }
      
      # Handle basis of record WITH CHOICES
      if (!is.null(query$basis_of_record)) {
        updateSelectizeInput(session, "filters-basis_of_record", 
                            choices = dropdowns$all_bor, 
                            selected = query$basis_of_record, 
                            server = TRUE)
      }
      
      # Handle life stage WITH CHOICES
      if (!is.null(query$life_stage)) {
        updateSelectizeInput(session, "filters-life_stage", 
                            choices = dropdowns$all_age, 
                            selected = query$life_stage, 
                            server = TRUE)
      }
      
      # Handle tab switching
      if (!is.null(query$tab)) {
        tab_name <- URLdecode(query$tab)
        updateNavbarPage(session, "main_tabs", selected = tab_name)
      }
      
      # Mark as processed
      url_processed(TRUE)
    }
  })
  
  # Dynamic download UI with warning for large datasets
  output[["filters-download_ui"]] <- renderUI({
    display_db <- filtered_database()
    
    if (is.null(display_db)) {
      return(downloadButton("filters-download_data", "Download Data", class = "btn-primary w-100", icon = icon("download")))
    }
    
    total_rows <- attr(display_db, "total_rows")
    if (is.null(total_rows)) total_rows <- nrow(display_db)
    
    if (total_rows >= 100000) {
      # Large dataset - show warning
      tagList(
        div(
          style = "background: #fff3cd; border: 1px solid #ffc107; border-radius: 4px; padding: 10px; margin-bottom: 10px;",
          icon("exclamation-triangle", style = "color: #856404;"),
          span(
            style = "color: #856404; margin-left: 5px; font-weight: bold;",
            sprintf("⚠️ Large download: %s rows", format(total_rows, big.mark = ","))
          )
        ),
        downloadButton(
          "filters-download_data",
          sprintf("Confirm & Download (%s rows)", format(total_rows, big.mark = ",")),
          class = "btn-warning w-100",
          icon = icon("download")
        )
      )
    } else {
      # Small dataset - direct download
      downloadButton("filters-download_data", "Download Data", class = "btn-primary w-100", icon = icon("download"))
    }
  })

  output[["filters-download_data"]] <- downloadHandler(
    filename = function() {
      paste("austraits-", Sys.Date(), ".zip", sep = "")
    },
    content = function(file) {
      # Clear memory caches before download
      full_filtered_cache(NULL)
      gc()
      
      tmpdir = tempfile(pattern="tempdir", fileext = ".dir")
      dir.create(tmpdir)
      csv_file <- file.path(tmpdir, "austraits-data.csv")
      bib_file <- file.path(tmpdir, "sources.bib")
      sources_file <- file.path(tmpdir, "sources.csv")
      html_file <- file.path(tmpdir, "usage.html")

      data_query <- download_data_table()

      if (is.null(data_query)) {
        data.frame(message = "No data selected") |> 
          utils::write.csv(csv_file, row.names = FALSE)
        writeLines("", bib_file)
        writeLines("<p>No data selected</p>", html_file)
      } else {
        arrow::write_csv_arrow(data_query, csv_file)
        
      # Only collect distinct keys, not full dataset
      keys <- data_query |> 
        dplyr::select(source_primary_key) |> 
        dplyr::distinct() |> 
        dplyr::collect() |> 
        dplyr::pull(source_primary_key) |>
        # This handles multiple keys pasted together with "; ", an issue for species averages
        stringr::str_split(pattern = "; ") |> unlist() |> sort() |> unique()

      sources |>
        dplyr::filter(source_primary_key %in% keys) |>
        arrow::write_csv_arrow(sources_file)

      export_bibtex_for_data(keys, bib_file)
        
      # Only collect a small sample for usage text to avoid memory crash
      total_rows <- attr(filtered_database(), "total_rows")
      if (is.null(total_rows)) total_rows <- nrow(filtered_database())

      if (!is.null(total_rows) && total_rows < 50000) {
        # Small dataset - generate full usage text
        sample_data <- data_query |> 
          dplyr::slice_head(n = 1000) |> 
          dplyr::collect()
        usage_text_content <- generate_usage_and_citations_text(sample_data)
        htmltools::save_html(usage_text_content, html_file)
        rm(sample_data)
        gc()
      } else {
        # Large dataset - skip usage text to save memory
        writeLines("<h3>Usage Information</h3><p>For large datasets, please refer to the AusTraits documentation at <a href='https://traitecoevo.github.io/austraits/'>https://traitecoevo.github.io/austraits/</a></p>", html_file)
      }
      }
        # Log download event
        log_telemetry_event("download", details = list(
        dataset_type = filters()$dataset_type,
        trait = filters()$trait_name
      ))
      showNotification("Downloading filtered data...",
                      type = "message",
                      duration = 3)

      zip::zip(
        zipfile = file, 
        files = list.files(tmpdir, full.names = TRUE), 
        mode = "cherry-pick"
      )

      unlink(tmpdir, recursive = TRUE)

      # Force garbage collection to free memory
      gc()
    },
    contentType = "application/zip"
  )
# Cleanup DuckDB connection when app stops
  onStop(function() {
    if (exists("duckdb_con")) {
      dbDisconnect(duckdb_con, shutdown = TRUE)
      cat("DuckDB connection closed\n")
    }
  })
}
