#' AusTraits Data Portal Server Logic
#'
#' @param input Input list generated by Shiny
#' @param output Output list generated by Shiny
#' @param session Session id for Shiny interaction

app_server <- function(input, output, session) {
  # Reactive value to store the filtered data later
  filtered_database <- reactiveVal(NULL)
  filtered_query_cache <- reactiveVal(NULL)
  full_filtered_cache <- reactiveVal(NULL)
  
  # Initialize dropdown choices
  taxon_name_choices <- reactive({
    all_taxon_names
  })
  genus_choices <- reactive({
    all_genus
  })
  family_choices <- reactive({
    all_family
  })
  
  # Update the appropriate selectizeInput when radio button changes
filters <- mod_filters_server(
  "filters",
  filtered_database,
  family_choices = family_choices,
  genus_choices = genus_choices,
  taxon_name_choices = taxon_name_choices
)
observeEvent(input[["filters-clear_filters"]], {
  updateSelectizeInput(session, "filters-trait_name", selected = character(0))
  updateSelectizeInput(session, "filters-basis_of_record", selected = character(0))
  updateSelectizeInput(session, "filters-life_stage", selected = character(0))
  updateSelectizeInput(session, "filters-apc_taxon_distribution", selected = character(0))
  
  # Force reload of all data after clearing
  Sys.sleep(0.1)  # Small delay to let inputs clear
  filtered_database(NULL)
})
  
  # Server-side selectizeInput update for other options that are not conditional
  updateSelectizeInput(session, "filters-trait_name", choices = all_traits, server = TRUE)
  updateSelectizeInput(session, "filters-basis_of_record", choices = all_bor, server = TRUE)
  updateSelectizeInput(session, "filters-life_stage", choices = all_age, server = TRUE)
  
  # Apply Filter
  observeEvent(filters(), {
    
    # SAFETY CHECK: Wait for data to be loaded
    req(exists("austraits_display"))
    if (!exists("austraits_display")) return()

    # Extract filters once
    filter_vals <- filters()

    # Check which filters are valid
    valid_filter_names <- valid_filters(filter_vals)

    has_filters <- any(
      sapply(valid_filter_names, function(name) {
        has_input_value(filter_vals, name)
      })
    )

    if (has_filters) {

      print("filtering")
      
      tryCatch({
        # Apply filters but don't collect yet
        filtered_query <- austraits_display |>
          apply_filters_categorical(filter_vals) |>
          apply_filters_location(filter_vals)
        
        # Get total count (fast - just counts, doesn't load data)
        total_rows <- filtered_query |> 
          dplyr::count() |> 
          dplyr::collect() |> 
          dplyr::pull(n)
        
        # Only collect first 100 rows for display
        filtered_data <- filtered_query |> 
          dplyr::slice_head(n = 100) |> 
          dplyr::collect()
        
        # Add total_rows as attribute so we can display it
        attr(filtered_data, "total_rows") <- total_rows
        # Query for loading more rows later
        filtered_query_cache(filtered_query)

        print(paste("done - showing 100 of", total_rows, "rows"))

        # Clear the full cache when filters change
        full_filtered_cache(NULL)

        # Store filtered data
        filtered_database(filtered_data)
        
      }, error = function(e) {
        cat("\n!!! FILTERING ERROR !!!\n")
        cat("Error:", e$message, "\n")
        cat("Available columns:", paste(names(austraits_display), collapse=", "), "\n")
        filtered_database(NULL)
      })

    } else {

      if (filter_vals$taxon_rank != "all") {
        filtered_database(NULL)
      }
    }
  })
    
# Display all data when all taxa are selected
  observeEvent(filters()$taxon_rank, {

    if (filters()$taxon_rank == "all" || filters()$taxon_rank == "") {
      
      # Get current filter values
      filter_vals <- filters()
      
      # Check if there are other filters applied (trait, location, etc.)
      has_other_filters <- any(
        !is.null(filter_vals$trait_name) && length(filter_vals$trait_name) > 0,
        !is.null(filter_vals$basis_of_record) && length(filter_vals$basis_of_record) > 0,
        !is.null(filter_vals$life_stage) && length(filter_vals$life_stage) > 0,
        !is.null(filter_vals$location) && filter_vals$location != "",
        !is.null(filter_vals$apc_taxon_distribution) && length(filter_vals$apc_taxon_distribution) > 0
      )
      
      if (has_other_filters) {
        # Apply filters even when "all taxa" is selected - ONLY LOAD 100 ROWS
        filtered_query <- austraits_display |>
          apply_filters_categorical(filter_vals) |>
          apply_filters_location(filter_vals)
        
        # Get total count
        total_rows <- filtered_query |> 
          dplyr::count() |> 
          dplyr::collect() |> 
          dplyr::pull(n)
        
        # Only collect first 100 rows
        filtered_data <- filtered_query |> 
          dplyr::slice_head(n = 100) |> 
          dplyr::collect()
        
        attr(filtered_data, "total_rows") <- total_rows
        filtered_query_cache(filtered_query)
        full_filtered_cache(NULL)
        
        filtered_database(filtered_data)
      } else {
        # Show full database - ONLY LOAD 100 ROWS
        all_data_query <- austraits_display
        
        # Get total count
        total_rows <- all_data_query |> 
          dplyr::count() |> 
          dplyr::collect() |> 
          dplyr::pull(n)
        
        # Only collect first 100 rows
        full_display_database <- all_data_query |> 
          dplyr::slice_head(n = 100) |> 
          dplyr::collect()
        
        attr(full_display_database, "total_rows") <- total_rows
        filtered_query_cache(all_data_query)
        full_filtered_cache(NULL)
        
        filtered_database(full_display_database)
      }

    } else {
      if (is.null(filtered_database())) {
        return()
      }
    }
  })
    
  # Set up download data as reactive expression
  download_data_table <- reactive({
    # Get the current filtered database that is on display
    display_db <- filtered_database()

    # Check if it's NULL and return appropriate value
    if (is.null(display_db)) {
      return(NULL)
    }
    
    # Assuming user has used column filtering: 
    # Get the row indices from the DT table that are currently visible
    # after filtering in the datatable
    if (!is.null(data_table_outputs$visible_rows())) {
      visible_rows <- data_table_outputs$visible_rows()
      
      # Subset the display data with the visible row indices
      display_db_filtered <- display_db[visible_rows, , drop = FALSE]
      
      # Join back up to full dataset to get all columns for only the visible rows
      return(austraits |> dplyr::semi_join(display_db_filtered, by = "row_id"))
    }
    
    # Default: Join back up to full dataset to get all columns
    austraits |> dplyr::semi_join(display_db, by = "row_id")
  })
  
  # Data table module
  data_table_outputs <- mod_data_table_server("data_table", filtered_database, filtered_query_cache, columns_display)

  # Reset pagination whenever filtered data changes (e.g. new filter)
  observeEvent(filtered_database(), {
    req(filtered_database())
    data_table_outputs$set_start(0)
  }, ignoreInit = TRUE)

  # Handle loading more data - with throttle to prevent rapid firing
  last_load_time <- reactiveVal(Sys.time())

  observeEvent(data_table_outputs$load_more_click(), {
    req(filtered_query_cache())
    
    current_data <- filtered_database()
    if (is.null(current_data)) return()
    
    total_loaded <- nrow(current_data)
    total_rows <- attr(current_data, "total_rows")
    
    if (is.null(total_rows) || total_loaded >= total_rows) return()
    
    cat("Loading next 100 rows... Currently have", total_loaded, "of", total_rows, "\n")
    
    # Check if we have full data cached
    cached_data <- full_filtered_cache()
    
    if (is.null(cached_data)) {
      cat("Caching full filtered dataset (this may take a moment)...\n")
      query <- filtered_query_cache()
      cached_data <- query |> dplyr::collect()
      full_filtered_cache(cached_data)
      cat("Cached", nrow(cached_data), "total rows\n")
    }
    
    # Get next 100 rows from cache
    end_row <- min(total_loaded + 100, nrow(cached_data))
    next_batch <- cached_data[(total_loaded + 1):end_row, ]
    
    cat("Loaded", nrow(next_batch), "new rows from cache\n")
    
    if (nrow(next_batch) > 0) {
      new_data <- dplyr::bind_rows(current_data, next_batch)
      attr(new_data, "total_rows") <- total_rows
      
      # Tell DT where to start (row index)
      data_table_outputs$set_start(total_loaded)

      # Re-render with more rows
      filtered_database(new_data)
      
      cat("Total rows now:", nrow(new_data), "\n")
    }
  }, ignoreInit = TRUE)

  # Citations module
  usage_text_reactive <- mod_citations_server("citations", filtered_database)

  # App info module
  mod_app_info_server("app_info")

  # Taxon view module
  mod_taxon_view_server("taxon_view", filters, filtered_database, reactive(input$main_tabs))

  # Trait view module
  mod_trait_view_server("trait_view", filtered_database, filters)

  # URL Query Parameter Handler - Load filters from URL on app startup
  url_processed <- reactiveVal(FALSE)

  observe({
    # Only run once
    if (url_processed()) return()
    
    query <- parseQueryString(session$clientData$url_search)
    
    # Only process if query parameters exist
    if (length(query) > 0) {
      
      # Handle taxon rank first
      if (!is.null(query$taxon_rank) && query$taxon_rank %in% c("all", "family", "genus", "taxon_name")) {
        updateRadioButtons(session, "filters-taxon_rank", selected = query$taxon_rank)
      }
      
      # Handle taxon selections WITH CHOICES
      if (!is.null(query$family)) {
        updateSelectizeInput(session, "filters-family", 
                            choices = family_choices(), 
                            selected = query$family, 
                            server = TRUE)
      }
      
      if (!is.null(query$genus)) {
        updateSelectizeInput(session, "filters-genus", 
                            choices = genus_choices(), 
                            selected = query$genus, 
                            server = TRUE)
      }
      
      if (!is.null(query$taxon_name)) {
        updateSelectizeInput(session, "filters-taxon_name", 
                            choices = taxon_name_choices(), 
                            selected = query$taxon_name, 
                            server = TRUE)
      }
      
      # Handle trait name WITH CHOICES
      if (!is.null(query$trait_name)) {
        updateSelectizeInput(session, "filters-trait_name", 
                            choices = all_traits, 
                            selected = query$trait_name, 
                            server = TRUE)
      }
      
      # Handle location filters
      if (!is.null(query$location) && query$location %in% c("georeferenced", "apc")) {
        updateRadioButtons(session, "filters-location", selected = query$location)
      }
      
      if (!is.null(query$apc_taxon_distribution)) {
        states <- strsplit(query$apc_taxon_distribution, ",")[[1]]
        updateSelectizeInput(session, "filters-apc_taxon_distribution", 
                            choices = all_states_territories, 
                            selected = states, 
                            server = TRUE)
      }
      
      # Handle basis of record WITH CHOICES
      if (!is.null(query$basis_of_record)) {
        updateSelectizeInput(session, "filters-basis_of_record", 
                            choices = all_bor, 
                            selected = query$basis_of_record, 
                            server = TRUE)
      }
      
      # Handle life stage WITH CHOICES
      if (!is.null(query$life_stage)) {
        updateSelectizeInput(session, "filters-life_stage", 
                            choices = all_age, 
                            selected = query$life_stage, 
                            server = TRUE)
      }
      
      # Handle tab switching
      if (!is.null(query$tab)) {
        tab_name <- URLdecode(query$tab)
        updateNavbarPage(session, "main_tabs", selected = tab_name)
      }
      
      # Mark as processed
      url_processed(TRUE)
    }
  })
  
  # Update info message about visible rows
  output[["filters-rows_info"]] <- renderUI({
    visible <- data_table_outputs$visible_rows()
    if (!is.null(visible)) {
      return(HTML(paste0("<span> Download will include ", length(visible), " observations.</span>")))
    }
    return(NULL)
  })
  
  # Download handler
  output[["filters-download_data"]] <- downloadHandler(
    filename = function() {
      paste("austraits-", Sys.Date(), ".zip", sep = "")
    },
    content = function(file) {
      tmpdir = tempfile(pattern="tempdir", fileext = ".dir")
      dir.create(tmpdir)
      csv_file <- file.path(tmpdir, "austraits-data.csv")
      bib_file <- file.path(tmpdir, "sources.bib")
      html_file <- file.path(tmpdir, "usage.html")

      data_query <- download_data_table()

      if (is.null(data_query)) {
        data.frame(message = "No data selected") |> 
          utils::write.csv(csv_file, row.names = FALSE)
        writeLines("", bib_file)
        writeLines("<p>No data selected</p>", html_file)
      } else {
        arrow::write_csv_arrow(data_query, csv_file)
        
        keys_data <- data_query |> 
          dplyr::select(source_primary_key) |> 
          dplyr::distinct() |> 
          dplyr::collect()
        
        keys <- keys_data$source_primary_key |> unique()
        export_bibtex_for_data(keys, bib_file)
        
        sample_data <- data_query |> dplyr::collect()
        usage_text_content <- generate_usage_and_citations_text(sample_data)
        htmltools::save_html(usage_text_content, html_file)
      }

      showNotification("Downloading filtered data...",
                      type = "message",
                      duration = 3)

      zip::zip(
        zipfile = file, 
        files = list.files(tmpdir, full.names = TRUE), 
        mode = "cherry-pick"
      )

      unlink(tmpdir, recursive = TRUE)
    },
    contentType = "application/zip"
  )
}
