#' AusTraits Data Portal Server Logic
#'
#' @param input Input list generated by Shiny
#' @param output Output list generated by Shiny
#' @param session Session id for Shiny interaction

app_server <- function(input, output, session) {
  # Reactive value to store the filtered data later
  filtered_database <- reactiveVal(NULL)
  filtered_query_cache <- reactiveVal(NULL)
  full_filtered_cache <- reactiveVal(NULL)

  loading_from_url <- reactiveVal(FALSE)

  # Reactive datasets that switch based on user selection
  current_austraits <- reactive({
    if (filters()$dataset_type == "species") {
      austraits_species_duckdb
    } else {
      austraits_duckdb
    }
  })

  current_austraits_display <- reactive({
    if (filters()$dataset_type == "species") {
      austraits_species_display_duckdb
    } else {
      austraits_display_duckdb
    }
  })

  current_columns_display <- reactive({
    if (filters()$dataset_type == "species") {
      columns_display_species
    } else {
      columns_display
    }
  })
  
  # Initialize dropdown choices
  taxon_name_choices <- reactive({
    dropdowns$all_taxon_names
  })
  genus_choices <- reactive({
    dropdowns$all_genus
  })
  family_choices <- reactive({
    dropdowns$all_family
  })

  # Start telemetry session
  start_telemetry_session()

# Update the appropriate selectizeInput when radio button changes
filters <- mod_filters_server(
  "filters",
  filtered_database,
  family_choices = family_choices,
  genus_choices = genus_choices,
  taxon_name_choices = taxon_name_choices,
  loading_from_url = loading_from_url
)
observeEvent(input[["filters-clear_filters"]], {
  updateSelectizeInput(session, "filters-trait_name", selected = character(0))
  updateSelectizeInput(session, "filters-basis_of_record", selected = character(0))
  updateSelectizeInput(session, "filters-life_stage", selected = character(0))
  updateSelectizeInput(session, "filters-apc_taxon_distribution", selected = character(0))
  
  # Force reload of all data after clearing
  Sys.sleep(0.1)  # Small delay to let inputs clear
  filtered_database(NULL)
})
  
  # Setup filter dropdown updates
  srv_filter_updates(input, output, session, filters, filtered_query_cache, current_austraits_display)

  # Debounce filters to prevent double-firing
  filters_debounced <- debounce(filters, 800)  # Wait 800ms for changes to settle
  
  # Apply all filters only once (after debounce)
  observeEvent(filters_debounced(), {
    if (loading_from_url()) return()
    start_time <- Sys.time()

    # SAFETY CHECK: Wait for data to be loaded
    req(exists("austraits_display") || exists("austraits_species_display"))
    if (!exists("austraits_display") && !exists("austraits_species_display")) return()


    cat("\n\n[FILTER] Start filtering...\n")
    parsed_filters <- parse_filters(filters())

    # # If no filters at all, show nothing (unless taxon_rank = "all")
    # if (!parsed_filters$has_filters && parsed_filters$taxon$taxon_rank != "all") {
    #   filtered_database(NULL)
    #   return()
    # }
    

    tryCatch({
      cat("[FILTER] Applying filters to dataset...\n")
      
      # Start with appropriate base dataset
      base_data <- current_austraits_display()
      
      # Apply all filters in ONE pass
      filtered_query <- apply_filters(base_data, parsed_filters)
      

      cat("[FILTER] Loading first 100 rows...\n")
      collect_start <- Sys.time()
      
      filtered_data <- filtered_query |> 
        utils::head(100) |> 
        dplyr::collect()
      
      elapsed_collect <- as.numeric(Sys.time() - collect_start, units = "secs")
      cat(sprintf("[FILTER] ✓ Data loaded: %d rows (%.2f sec)\n", 
          nrow(filtered_data), elapsed_collect))
      
      # Set temporary NA while counting
      attr(filtered_data, "total_rows") <- NA
      filtered_query_cache(filtered_query)
      full_filtered_cache(NULL)
      
      # Display table immediately
      filtered_database(filtered_data)
      
      cat(sprintf("[FILTER] 🚀 TABLE DISPLAYED in %.2f sec\n", elapsed_collect))
      

      cat("[FILTER] Counting total rows...\n")
      count_start <- Sys.time()
      
      total_rows <- filtered_query |> 
        dplyr::count() |> 
        dplyr::collect() |> 
        dplyr::pull(n)
      
      elapsed_count <- as.numeric(Sys.time() - count_start, units = "secs")
      cat(sprintf("[FILTER] ✓ Count complete: %s rows (%.2f sec)\n", 
          format(total_rows, big.mark = ","), elapsed_count))
      
      # Update with actual count
      attr(filtered_data, "total_rows") <- total_rows
      filtered_database(filtered_data)
      
      elapsed_total <- as.numeric(Sys.time() - start_time, units = "secs")
      cat(sprintf("[FILTER] ✅ COMPLETE in %.2f sec (parse + filter + display + count)\n", elapsed_total))
      
    }, error = function(e) {
      cat("\n!!! FILTERING ERROR !!!\n")
      cat("Error:", e$message, "\n")
      cat("Parsed filters:\n")
      print(parsed_filters)
      filtered_database(NULL)
    })
  })
  
  # Data table module
  data_table_outputs <- mod_data_table_server("data_table", filtered_database, filtered_query_cache, current_columns_display)

  # download handlers
  srv_download(input, output, session, filtered_database, filtered_query_cache, current_austraits, filters, data_table_outputs, full_filtered_cache)

# Reset pagination whenever filtered data changes (e.g. new filter)
  observeEvent(filtered_database(), {
    req(filtered_database())
    data_table_outputs$set_start(0)

    # Log search event
    log_telemetry_event("search", details = list(
    dataset_type = filters()$dataset_type,
    trait = filters()$trait_name
  ))
  }, ignoreInit = TRUE)

  # Handle loading more data - with throttle to prevent rapid firing
  last_load_time <- reactiveVal(Sys.time())

  observeEvent(data_table_outputs$load_more_click(), {
    req(filtered_query_cache())
    
    current_data <- filtered_database()
    if (is.null(current_data)) return()
    
    total_loaded <- nrow(current_data)
    total_rows <- attr(current_data, "total_rows")
    
    if (is.null(total_rows) || total_loaded >= total_rows) return()
    
    cat("Loading next 100 rows... Currently have", total_loaded, "of", total_rows, "\n")
    
    # Check if we have full data cached
    cached_data <- full_filtered_cache()
    
    if (is.null(cached_data)) {
      cat("Caching full filtered dataset (this may take a moment)...\n")
      query <- filtered_query_cache()
      cached_data <- query |> dplyr::collect()
      full_filtered_cache(cached_data)
      cat("Cached", nrow(cached_data), "total rows\n")
    }
    
    # Get next 100 rows from cache
    end_row <- min(total_loaded + 100, nrow(cached_data))
    next_batch <- cached_data[(total_loaded + 1):end_row, ]
    
    cat("Loaded", nrow(next_batch), "new rows from cache\n")
    
    if (nrow(next_batch) > 0) {
      new_data <- dplyr::bind_rows(current_data, next_batch)
      attr(new_data, "total_rows") <- total_rows
      
      # Tell DT where to start (row index)
      data_table_outputs$set_start(total_loaded)

      # Re-render with more rows
      filtered_database(new_data)
      
      cat("Total rows now:", nrow(new_data), "\n")
    }
  }, ignoreInit = TRUE)

  # Citations module (only active when tab is selected)
  usage_text_reactive <- mod_citations_server("citations", filtered_query_cache, reactive(input$main_tabs))

  # App info module
  mod_app_info_server("app_info")

  # Taxon view module
  mod_taxon_view_server("taxon_view", filters, filtered_database, reactive(input$main_tabs))

  # Trait view module
  mod_trait_view_server("trait_view", filtered_query_cache, filters)

  # URL parameter handling
  srv_url_params(input, output, session, family_choices, genus_choices, taxon_name_choices, loading_from_url)
  
# Cleanup DuckDB connection when app stops
  onStop(function() {
    if (exists("duckdb_con")) {
      dbDisconnect(duckdb_con, shutdown = TRUE)
    }
  })
}
