#' AusTraits Data Portal Server Logic
#'
#' @param input Input list generated by Shiny
#' @param output Output list generated by Shiny
#' @param session Session id for Shiny interaction

austraits_server <- function(input, output, session) {
  # Reactive value to store the filtered data later
  filtered_database <- reactiveVal(NULL)
  
  # Initialize dropdown choices
  taxon_name_choices <- reactive({
    all_taxon_names
  })
  genus_choices <- reactive({
    all_genus
  })
  family_choices <- reactive({
    all_family
  })
  
  # Update the appropriate selectizeInput when radio button changes
filters <- mod_filters_server(
  "filters",
  filtered_database,
  family_choices = family_choices,
  genus_choices = genus_choices,
  taxon_name_choices = taxon_name_choices
)
observeEvent(input[["filters-clear_filters"]], {
  updateSelectizeInput(session, "filters-trait_name", selected = character(0))
  updateSelectizeInput(session, "filters-basis_of_record", selected = character(0))
  updateSelectizeInput(session, "filters-life_stage", selected = character(0))
  updateSelectizeInput(session, "filters-apc_taxon_distribution", selected = character(0))
  
  # Force reload of all data after clearing
  Sys.sleep(0.1)  # Small delay to let inputs clear
  filtered_database(NULL)
})
  
  # Server-side selectizeInput update for other options that are not conditional
  updateSelectizeInput(session, "filters-trait_name", choices = all_traits, server = TRUE)
  updateSelectizeInput(session, "filters-basis_of_record", choices = all_bor, server = TRUE)
  updateSelectizeInput(session, "filters-life_stage", choices = all_age, server = TRUE)
  
  # Apply Filter
  observeEvent(filters(), {


  # Extract filters once
  filter_vals <- filters()

  # Check which filters are valid
  valid_filter_names <- valid_filters(filter_vals)

  has_filters <- any(
    sapply(valid_filter_names, function(name) {
      has_input_value(filter_vals, name)
    })
  )

  if (has_filters) {

    print("filtering")

    filtered_data <- austraits_display |>
      apply_filters_categorical(filter_vals) |>
      apply_filters_location(filter_vals) |>
      dplyr::collect()

    print("done")

    # Store filtered data
    filtered_database(filtered_data)

  } else {

    if (filter_vals$taxon_rank != "all") {
      filtered_database(NULL)
    }
  }
})
    
# Display all data when all taxa are selected
  observeEvent(filters()$taxon_rank, {

    if (filters()$taxon_rank == "all" || filters()$taxon_rank == "") {
      
      # Get current filter values
      filter_vals <- filters()
      
      # Check if there are other filters applied (trait, location, etc.)
      has_other_filters <- any(
        !is.null(filter_vals$trait_name) && length(filter_vals$trait_name) > 0,
        !is.null(filter_vals$basis_of_record) && length(filter_vals$basis_of_record) > 0,
        !is.null(filter_vals$life_stage) && length(filter_vals$life_stage) > 0,
        !is.null(filter_vals$location) && filter_vals$location != "",
        !is.null(filter_vals$apc_taxon_distribution) && length(filter_vals$apc_taxon_distribution) > 0
      )
      236
      if (has_other_filters) {
        # Apply filters even when "all taxa" is selected
        filtered_data <- austraits_display |>
          apply_filters_categorical(filter_vals) |>
          apply_filters_location(filter_vals) |>
          dplyr::collect()
        
        filtered_database(filtered_data)
      } else {
        # Show full database only if no other filters
        full_display_database <- austraits_display |> dplyr::collect()
        filtered_database(full_display_database)
      }

    } else {
      if (is.null(filtered_database())) {
        return()
      }
    }
  })
    
  # Set up download data as reactive expression
  download_data_table <- reactive({
    # Get the current filtered database that is on display
    display_db <- filtered_database()

    # Check if it's NULL and return appropriate value
    if (is.null(display_db)) {
      return(NULL)
    }
    
    # Assuming user has used column filtering: 
    # Get the row indices from the DT table that are currently visible
    # after filtering in the datatable
    if (!is.null(data_table_outputs$visible_rows())) {
      visible_rows <- data_table_outputs$visible_rows()
      
      # Subset the display data with the visible row indices
      display_db_filtered <- display_db[visible_rows, , drop = FALSE]
      
      # Join back up to full dataset to get all columns for only the visible rows
      return(austraits |> dplyr::semi_join(display_db_filtered, by = "row_id")  |> dplyr::collect())
    }
    
    # Default: Join back up to full dataset to get all columns
    austraits |> dplyr::semi_join(display_db, by = "row_id") |> dplyr::collect()
  })
  
  # Data table module
  data_table_outputs <- mod_data_table_server("data_table", filtered_database, columns_display)

  # Citations module
  usage_text_reactive <- mod_citations_server("citations", filtered_database)

  # App info module
  mod_app_info_server("app_info")

  # Taxon view module
  mod_taxon_view_server("taxon_view", filters, filtered_database, reactive(input$main_tabs))

  # Trait view module
  mod_trait_view_server("trait_view", filtered_database, filters)
  
  # Update info message about visible rows
  output[["filters-rows_info"]] <- renderUI({
    visible <- data_table_outputs$visible_rows()
    if (!is.null(visible)) {
      return(HTML(paste0("<span> Download will include ", length(visible), " observations.</span>")))
    }
    return(NULL)
  })
  
  # Download handler
  output[["filters-download_data"]] <- downloadHandler(
    filename = function() {
      paste("austraits-", Sys.Date(), ".zip", sep = "")
    },
    content = function(file) {
      # Create a temporary directory that will hold the zip file contents
      # A new temp directory is made since the one returned by tempdir() is in use
      # by other libraries
      tmpdir = tempfile(pattern="tempdir", fileext = ".dir")
      dir.create(tmpdir)
      csv_file <- file.path(tmpdir, "austraits-data.csv")
      bib_file <- file.path(tmpdir, "sources.bib")
      html_file <- file.path(tmpdir, "usage.html")

      # Get the current download data with datatable filtering applied
      data_to_download <- download_data_table()

      # Handle NULL or empty data case
      if (is.null(data_to_download) || nrow(data_to_download) == 0) {
        data_to_download <- data.frame(message = "No data selected")
      }

      # Download austraits data
      utils::write.csv(data_to_download, csv_file, row.names = FALSE)

      # Export bibtex from the filtered data
      keys <- data_to_download$source_primary_key |> unique()
      export_bibtex_for_data(keys, bib_file)

      # Update the usage text and convert to html
      usage_text_content <- generate_usage_and_citations_text(data_to_download)
      htmltools::save_html(usage_text_content, html_file)

      # Show notification
      showNotification("Downloading filtered data...",
                       type = "message",
                       duration = 3)

      zip::zip(
        zipfile = file, 
        files = list.files(tmpdir, full.names = TRUE), 
        mode = "cherry-pick"
      )

      # Clean up temporary directory
      unlink(tmpdir, recursive = TRUE)
    },
    contentType = "application/zip"
  )
}
