#' AusTraits Data Portal Server Logic
#'
#' @param input Input list generated by Shiny
#' @param output Output list generated by Shiny
#' @param session Session id for Shiny interaction

austraits_server <- function(input, output, session) {
  # Reactive value to store the filtered data later
  filtered_database <- reactiveVal(NULL)
  
  # New reactive value to store datatable filter state
  dt_proxy <- reactiveVal(NULL)

  # Contains the data usage text 
  usage_text <- reactiveVal(NULL)
  
  # Contains the taxon text
  taxon_text <- reactiveVal(NULL)
  output$taxon_text <- renderUI({
    req(taxon_text())
    HTML(commonmark::markdown_html(taxon_text()))
  })

  # Initialize dropdown choices
  taxon_name_choices <- reactive({
    all_taxon_names
  })
  genus_choices <- reactive({
    all_genus
  })
  family_choices <- reactive({
    all_family
  })
  
  # Update the appropriate selectizeInput when radio button changes
filters <- mod_filters_server(
  "filters",
  filtered_database,
  family_choices = family_choices,
  genus_choices = genus_choices,
  taxon_name_choices = taxon_name_choices
)
  
  # Server-side selectizeInput update for other options that are not conditional
  updateSelectizeInput(session, "filters-trait_name", choices = all_traits, server = TRUE)
  updateSelectizeInput(session, "filters-basis_of_record", choices = all_bor, server = TRUE)
  updateSelectizeInput(session, "filters-life_stage", choices = all_age, server = TRUE)
  
  # Apply Filter
  observeEvent(filters(), {


  # Extract filters once
  filter_vals <- filters()

  # Check which filters are valid
  valid_filter_names <- valid_filters(filter_vals)

  has_filters <- any(
    sapply(valid_filter_names, function(name) {
      has_input_value(filter_vals, name)
    })
  )

  if (has_filters) {

    print("filtering")

    filtered_data <- austraits_display |>
      apply_filters_categorical(filter_vals) |>
      apply_filters_location(filter_vals) |>
      dplyr::collect()

    print("done")

    # Usage / citations
    usage_text(generate_usage_and_citations_text(filtered_data))
    output$usage_text <- renderUI({ usage_text() })

    # Trait profile
    trait_profile <- generate_trait_profile(filtered_data)

    output$trait_profile <- renderUI({
      tagList(trait_profile[[1]])
    })

    output$trait_histogram_text <- renderUI({
      tagList(
        p(
          "The plot below shows the distribution of selected data for this trait, including data collected on individuals of all age classes (seedling, sapling, adult), both field-collected and experimental data, and data representing individuals and population means."
        ),
        p(
          "Visualising data records across the families with the most data for the trait indicates the taxonomic breadth of information for this trait"
        )
      )
    })

    output$trait_beeswarm_plot <- plotly::renderPlotly({
      req(filtered_data, filter_vals$trait_name)
      plot_trait_distribution(filtered_data, filter_vals$trait_name) |>
        plotly::ggplotly(
          tooltip = c("x", "y", "text"),
          height = 400
        )
    })

    output$trait_geo_text <- renderUI({
      trait_profile[[3]]
    })

    output$trait_geo_map <- leaflet::renderLeaflet({
      trait_profile[[4]]
    })

    # Store filtered data
    filtered_database(filtered_data)

  } else {

    if (filter_vals$taxon_rank != "all") {
      filtered_database(NULL)
    }

    output$trait_profile <- renderUI({
      HTML("Please select a single trait to view.")
    })
  }
})
    
# Display all data when all taxa are selected
  observeEvent(filters()$taxon_rank, {

    if (filters()$taxon_rank == "all") {
      
      # Get current filter values
      filter_vals <- filters()
      
      # Check if there are other filters applied (trait, location, etc.)
      has_other_filters <- any(
        !is.null(filter_vals$trait_name) && length(filter_vals$trait_name) > 0,
        !is.null(filter_vals$basis_of_record) && length(filter_vals$basis_of_record) > 0,
        !is.null(filter_vals$life_stage) && length(filter_vals$life_stage) > 0,
        !is.null(filter_vals$location) && filter_vals$location != "",
        !is.null(filter_vals$apc_taxon_distribution) && length(filter_vals$apc_taxon_distribution) > 0
      )
      
      if (has_other_filters) {
        # Apply filters even when "all taxa" is selected
        filtered_data <- austraits_display |>
          apply_filters_categorical(filter_vals) |>
          apply_filters_location(filter_vals) |>
          dplyr::collect()
        
        filtered_database(filtered_data)
      } else {
        # Show full database only if no other filters
        full_display_database <- austraits_display |> dplyr::collect()
        filtered_database(full_display_database)
      }

    } else {
      if (is.null(filtered_database())) {
        return()
      }
    }
  })

  # Check the taxon_name selection when switching to "Taxon View" tab
  observeEvent(
    list(input$main_tabs, filters()),
    {
      # Only act when Taxon View tab is active
      req(input$main_tabs == "Taxon View")

      filter_vals <- filters()

      # Must be in taxon_name mode with exactly 1 selected taxon
      if (filter_vals$taxon_rank != "taxon_name" ||
          is.null(filter_vals$taxon_name) ||
          length(filter_vals$taxon_name) != 1) {

        taxon_text(NULL)
        showNotification(
          "Taxon View needs Taxon rank = Taxon name and exactly 1 taxon selected.",
          type = "warning",
          duration = 3
        )
        return()
      }

      selected_taxon <- filter_vals$taxon_name[[1]]

      # Prefer current filtered DB, otherwise fetch
      data <- filtered_database()
      if (is.null(data)) {
        data <- austraits_display |>
          apply_filters_categorical(filter_vals) |>
          dplyr::collect()
        filtered_database(data)
      }

      if (nrow(data) == 0) {
        taxon_text(NULL)
        showNotification(
          "No data available for the selected taxon name",
          type = "warning",
          duration = 5
        )
        return()
      }

      # Generate taxon text

      txt <- generate_taxon_text(data, selected_taxon)

      # Collapse if it's a vector, check if empty
      if (is.null(txt) || length(txt) == 0 || all(nchar(txt) == 0)) {
        taxon_text(NULL)
        showNotification(
          "Taxon profile text came back empty (generate_taxon_text returned nothing).",
          type = "error",
          duration = 6
        )
        return()
      }

      # Collapse the vector into a single string if needed
      if (length(txt) > 1) {
        txt <- paste(txt, collapse = "\n\n")
      }

      taxon_text(txt)

    },
    ignoreInit = TRUE
  )

  # Clear filters button action
  observeEvent(input[["filters-clear_filters"]], {
    
  # Check if any filters are currently applied
  filter_vals <- filters()

  filters_applied <- any(
    vapply(filter_vals, function(x) !is.null(x) && length(x) > 0, logical(1))
  )
  
  if (!filters_applied) {
    # Show a notification if no filters are applied
    showNotification("No filters are currently applied",
                     type = "warning",
                     duration = 3)
    return() # Exit the observer early
  }

    # Based on which filter is currently active
    if (filter_vals$taxon_rank == "taxon_name") {
      updateSelectizeInput(
        session,
        "taxon_name",
        choices = taxon_name_choices(),
        selected = NULL,
        server = TRUE
      )
    } else if (filter_vals$taxon_rank == "genus") {
      updateSelectizeInput(
        session,
        "genus",
        choices = genus_choices(),
        selected = NULL,
        server = TRUE
      )
    } else if (filter_vals$taxon_rank == "family") {
      updateSelectizeInput(
        session,
        "family",
        choices = family_choices(),
        selected = NULL,
        server = TRUE
      )
    }
    
    # Clear the other filters that are not conditional
    updateSelectizeInput(session, "filters-trait_name", choices = all_traits, server = TRUE)
    updateSelectizeInput(session, "filters-basis_of_record", choices = all_bor, server = TRUE)
    updateSelectizeInput(session, "filters-life_stage", choices = all_age, server = TRUE)
    updateSelectizeInput(session, "filters-apc_taxon_distribution", choices = all_states_territories, server = TRUE)
    
    # Set the filtered database to NULL
    filtered_database(NULL)

    # Reset the download data to NULL
    download_data_table <- reactive({
      NULL
    })
 
    # Reset datatable filters
    if (!is.null(dt_proxy())) {
      DT::replaceData(dt_proxy(), filtered_database())
    }

    # Reset the usage text
    usage_text(NULL)
    
    # Show notification
    showNotification("Filters have been cleared",
                     type = "message",
                     duration = 3
    )
  })
    
  # Set up download data as reactive expression
  download_data_table <- reactive({
    # Get the current filtered database that is on display
    display_db <- filtered_database()

    # Check if it's NULL and return appropriate value
    if (is.null(display_db)) {
      return(NULL)
    }
    
    # Assuming user has used column filtering: 
    # Get the row indices from the DT table that are currently visible
    # after filtering in the datatable
    if (!is.null(input$data_table_rows_all)) {
      # Get all visible row indices after filtering
      visible_rows <- input$data_table_rows_all
      
      # Subset the display data with the visible row indices
      display_db_filtered <- display_db[visible_rows, , drop = FALSE]
      
      # Join back up to full dataset to get all columns for only the visible rows
      return(austraits |> dplyr::semi_join(display_db_filtered, by = "row_id")  |> dplyr::collect())
    }
    
    # Default: Join back up to full dataset to get all columns
    austraits |> dplyr::semi_join(display_db, by = "row_id") |> dplyr::collect()
  })
  
  # Render user selected data table output
  output$data_table <- DT::renderDT({
    # Get the display data
    print("collecting austraits display data")
    display_data <- filtered_database()
    print("done")

    # Return NULL or empty table if no data
    if (is.null(display_data)) {
      return(datatable(data.frame(), options = list(pageLength = 10)))
    }
    
    # Determine column indices where we want to turn off column filtering
    no_filter_cols <- which(names(display_data) %in% c("value", "unit", "entity_type", "value_type", "replicates"))
    # Hide the row_id column
    hide_cols <- which(names(display_data) %not_in% columns_display)
    # Truncate these columns
    thin_cols <- which(names(display_data) %not_in% c("taxon_name", "trait_name", "genus", "family"))
    dt <- datatable(
      data = display_data,
      escape = FALSE,
      rownames = FALSE,
      filter = "top",
      class = "cell-border stripe nowrap",
      options = list(
        pageLength = 10,
        searching = FALSE,
        autoWidth = FALSE,
        scrollX = TRUE,
        columnDefs = list(
          list(
            targets = no_filter_cols - 1, # Targets denotes the columns index where filter will be switched off - Note that JS is 0 indexing
            searchable = FALSE
          ),
          list(
            targets = hide_cols - 1, # Hide these columns from table view
            visible = FALSE
          ),
          list(
            targets = thin_cols - 1, # Force these columns to have a smaller width
            className = "truncated"
          )
        ),
        # Add server-side processing for better filtering performance
        serverSide = FALSE # Keep this as FALSE for client-side filtering to access filtered rows
      ),
      # Removed selection = 'multiple' option
    )
    
    # Store the DT proxy for later use
    dt_proxy(DT::dataTableProxy("data_table"))
    
    return(dt)
  })
  
  # Update info message about visible rows
  output[["filters-rows_info"]] <- renderUI({
    # Get the number of rows currently displayed after filtering
    if (!is.null(input$data_table_rows_all)) {
      total_visible <- length(input$data_table_rows_all)
      return(HTML(paste0("<span> Download will include ", total_visible, " observations.</span>")))
    }
    return(NULL)
  })
  
  # Download handler
  output[["filters-download_data"]] <- downloadHandler(
    filename = function() {
      paste("austraits-", Sys.Date(), ".zip", sep = "")
    },
    content = function(file) {
      # Create a temporary directory that will hold the zip file contents
      # A new temp directory is made since the one returned by tempdir() is in use
      # by other libraries
      tmpdir = tempfile(pattern="tempdir", fileext = ".dir")
      dir.create(tmpdir)
      csv_file <- file.path(tmpdir, "austraits-data.csv")
      bib_file <- file.path(tmpdir, "sources.bib")
      html_file <- file.path(tmpdir, "usage.html")

      # Get the current download data with datatable filtering applied
      data_to_download <- download_data_table()

      # Handle NULL or empty data case
      if (is.null(data_to_download) || nrow(data_to_download) == 0) {
        data_to_download <- data.frame(message = "No data selected")
      }

      # Download austraits data
      utils::write.csv(data_to_download, csv_file, row.names = FALSE)

      # Export bibtex from the filtered data
      keys <- data_to_download$source_primary_key |> unique()
      export_bibtex_for_data(keys, bib_file)

      # Update the usage text and convert to html
      usage_text(generate_usage_and_citations_text(data_to_download))
      htmltools::save_html(usage_text(), html_file)

      # Show notification
      showNotification("Downloading filtered data...",
                       type = "message",
                       duration = 3)

      zip::zip(
        zipfile = file, 
        files = list.files(tmpdir, full.names = TRUE), 
        mode = "cherry-pick"
      )

      # Clean up temporary directory
      unlink(tmpdir, recursive = TRUE)
    },
    contentType = "application/zip"
  )
}
