#' User interface (UI) for AusTraits Data Portal

austraits_ui <- function(){
  
  ui <- page_sidebar(
    
    # Set the overall theme of the app
    theme = bs_theme(preset = "flatly"),
    
    # Title of the portal
    title = "AusTraits Data Portal",
    
    # Create a sidebar for the app
    sidebar = sidebar(
      # Filter by taxonomic information
      h5("Taxonomic information"),
      
      radioButtons("user_taxon_rank", 
                   label = "Filter by which taxon rank:",
                   choices = c('Taxon name' = "taxon_name",
                               'Genus' = "genus", 
                               'Family' = "family"
                   )
      ),
      
      # Only show this panel if Taxon name is selected
      conditionalPanel(
        condition = 'input.user_taxon_rank == "taxon_name"',
        ## By taxon_name
        selectizeInput("user_taxon_name",
                       label = "Taxon name:",
                       choices = NULL,
                       multiple = TRUE)
      ),
      
      # Only show this panel if Genus is selected
      conditionalPanel(
        condition = 'input.user_taxon_rank == "genus"',
        ## By genus
        selectizeInput("user_genus",
                       label = "Genus:",
                       choices = NULL,
                       multiple = TRUE
        )
      ),
      # Only show this panel if family is selected  
      conditionalPanel(
        condition = 'input.user_taxon_rank == "family"',
        ## By family
        selectizeInput("user_family",
                       label = "Family:",
                       choices = NULL,
                       multiple = TRUE
        )
      ),
      
      h5("Contexts information"),
      
      ## By context property
      selectizeInput("user_context_property",
                     label = "Search contexts by keywords",
                     choices = NULL,
                     multiple = TRUE
      ),
      
      br(),
      actionButton("clear_filters", "Clear Filters", 
                   class = "btn-warning w-100"),
      
      # Download button
      downloadButton("download_data", "Download displayed data")
    ),
    
    # Data display
    card(
      card_header("Data Preview"),
      card_body(
        fillable = TRUE,
        DT::DTOutput("data_table")
      )
    )
  )
}


#' AusTraits Data Portal Server Logic
#'
#' @param input Input list generated by Shiny
#' @param output Output list generated by Shiny
#' @param session Session id for Shiny interaction

austraits_server <- function(input, output, session) {
  # Initialize dropdown choices for taxonomic information
  taxon_name_choices <- reactive({ all_taxon_names })
  genus_choices <- reactive({ all_genus })
  family_choices <- reactive({ all_family })
  
  # Reactive value to store the filtered data later
  filtered_database <- reactiveVal(NULL)
  
  # Update the appropriate selectizeInput when radio button changes
  observeEvent(input$user_taxon_rank, {
    # Reset the filtered database to clear the data preview
    filtered_database(NULL)
    
    if(input$user_taxon_rank == "taxon_name") {
      updateSelectizeInput(
        session,
        "user_taxon_name",
        choices = taxon_name_choices(),
        selected = NULL,
        server = TRUE
      )
    } else if(input$user_taxon_rank == "genus") {
      updateSelectizeInput(
        session,
        "user_genus",
        choices = genus_choices(),
        selected = NULL,
        server = TRUE
      )
    } else if(input$user_taxon_rank == "family") {
      updateSelectizeInput(
        session,
        "user_family",
        choices = family_choices(),
        selected = NULL,
        server = TRUE
      )
    }
  })
  
  # Filter data by taxonomic information
  ## Watch for changes in user_taxon_name
  observeEvent(input$user_taxon_name, {
    # Skip if empty
    if(length(input$user_taxon_name) == 0) {
      filtered_database(NULL)
      return()
    }
    
    # Filter by taxonomic info
    filtered_by_taxonomy <- austraits |> 
      extract_taxa(taxon_name = input$user_taxon_name)
    
    # Store in reactive
    filtered_database(filtered_by_taxonomy)
  })
  
  ## Watch for changes in user-genus
  observeEvent(input$user_genus, {
    # Skip if empty
    if(length(input$user_genus) == 0) {
      filtered_database(NULL)
      return()
    }
    
    # Filter by taxonomic info
    filtered_by_taxonomy <- austraits |> 
      extract_taxa(genus = input$user_genus)
    
    # Store in reactive
    filtered_database(filtered_by_taxonomy)
  })
  
  ## Watch for changes in user-family
  observeEvent(input$user_family, {
    # Skip if empty
    if(length(input$user_family) == 0) {
      filtered_database(NULL)
      return()
    }
    
    # Filter by taxonomic info
    filtered_by_taxonomy <- austraits |> 
      extract_taxa(family = input$user_family)
    
    # Store in reactive
    filtered_database(filtered_by_taxonomy)
  })
  
  # Filter data by contexts information
  updateSelectizeInput(
    session,
    "user_context_property",
    choices = all_contexts,
    selected = NULL,
    server = TRUE
  )
  
  observeEvent(input$user_context_property, {
    # Skip if empty
    if(length(input$user_taxon_name) == 0) {
      filtered_database(NULL)
      return()
    }
    
    # Filter by taxonomic info
    filtered_by_contexts <- austraits |> 
      extract_data(table = "contexts",
                   col = "context_property", 
                   col_value = input$user_context_property)
    
    # Store in reactive
    filtered_database(filtered_by_contexts)
  })
  
  # Clear filters button action
  observeEvent(input$clear_filters, {
    # Based on which filter is currently active
    if(input$user_taxon_rank == "taxon_name") {
      updateSelectizeInput(
        session,
        "user_taxon_name",
        choices = taxon_name_choices(),
        selected = NULL,
        server = TRUE
      )
    } else if(input$user_taxon_rank == "genus") {
      updateSelectizeInput(
        session,
        "user_genus",
        choices = genus_choices(),
        selected = NULL,
        server = TRUE
      )
    } else if(input$user_taxon_rank == "family") {
      updateSelectizeInput(
        session,
        "user_family",
        choices = family_choices(),
        selected = NULL,
        server = TRUE
      )
    }
    
    # Store nothing in filtered_data()
    filtered_database(NULL)
    
    # Show notification
    showNotification("Filters have been cleared", 
                     type = "message", 
                     duration = 3)
  })
  
  # Set up display data as reactive expression
  display_data_table <- reactive({
    # Get the current filtered database
    filtered_db <- filtered_database()
    
    # Check if it's NULL and return appropriate value
    if (is.null(filtered_db)) {
      return(NULL)
    }
    
    # Format the database for display
    format_database_for_display(filtered_db)
  })
  
  # Set up download data as reactive expression  
  download_data_table <- reactive({
    # Get the current filtered database
    filtered_db <- filtered_database()
    
    # Check if it's NULL and return appropriate value
    if (is.null(filtered_db)) {
      return(NULL)
    }
    
    # Format the database for download
    format_database_for_download(filtered_db)
  })
  
  # Render user selected data table output
  output$data_table <- DT::renderDT({
    # Get the display data
    display_data <- display_data_table()
    
    # Return NULL or empty table if no data
    if (is.null(display_data)) {
      return(datatable(data.frame(), options = list(pageLength = 10)))
    }
    
    datatable(
      data = display_data,
      options = list(
        pageLength = 10,
        scrollX = TRUE
      ),
      rownames = FALSE,
      filter = 'none',
      class = 'cell-border stripe'
    )
  })
  
  # Download handler
  output$download_data <- downloadHandler(
    filename = function() {
      paste("austraits-6.0.0-", Sys.Date(), ".csv", sep = "")
    },
    content = function(file) {
      # Get the current download data
      data_to_download <- download_data_table()
      
      # Handle NULL or empty data case
      if (is.null(data_to_download) || nrow(data_to_download) == 0) {
        data_to_download <- data.frame(message = "No data selected")
      }
      
      utils::write.csv(data_to_download, file, row.names = FALSE)
    }
  )
}